version: '3.8'

services:
  frontend:
    build: ./frontend/bookmark-frontend
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./frontend/bookmark-frontend:/app
    command: ["npm","run","start"]


  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - NODE_ENV=production